### ISSUE TITLE
請問，172.txt這個文件改動後的文件檢驗是如何通過的

### ISSUE THREAD

**Issue by CSJJ666** [FuXiaoGuo/Android#1]
我想添加一些我知道的服裝到遊戲中。我知道Fuxiao這個文件夾裡的內容一個是hash表，另一個則是陸奧的皮膚，如果要添加的話，顯然要更新172.txt這個文件的hash表，但是我發現當我改動它的時候，就會在遊戲裡報錯，顯然這個文件是被校驗的。請問您是如何校驗這個文件的，謝謝。

**Comment by FuXiaoGuo** [comment]
確實是有校驗的，不過沒有公開的打算。原因是公開意味著所有人可以隨意替換資源，遊戲資源被替換之後，遊戲中是無法識別出來的。之前就有發生過惡意替換資源，發佈視頻和截圖，給官方帶來不利影響的例子。可能造成不利影響，違反了我製作這個替換的初衷。還希望能理解。

**Comment by FuXiaoGuo** [comment]
我不會去自創任何資源，僅僅只是將台服使用的資源搬過來。

**Comment by CSJJ666** [comment]
好吧，既然如此希望你能把光輝的皮也加進去。她在
hash表裡的表頭是art/charcg/8008。文件名是01326729993083268628.byte。
另外台服的資源在data/data裡面又藏了一批，並不是都在asset那個apk包裡能找到。這些都是角色的原版皮膚，我後續會整理個表格出來，希望您能盡量將所有不同的皮膚都替換成台服版本，謝謝！

**Comment by FuXiaoGuo** [comment]
> 好吧，既然如此希望你能把光輝的皮也加進去。她在 hash表裡的表頭是art/charcg/8008。文件名是01326729993083268628.byte。 另外台服的資源在data/data裡面又藏了一批，並不是都在asset那個apk包裡能找到。這些都是角色的原版皮膚，我後續會整理個表格出來，希望您能盡量將所有不同的皮膚都替換成台服版本，謝謝！

已經更新，目前可以認為是全部船的資源都替換了。
